BOOGIEROOT=..\..\..\boogie
BOOGIEBINDIR = Binaries

all:
	copy /y "$(BOOGIEROOT)\$(BOOGIEBINDIR)\CodeContractsExtender.dll"
	copy /y "$(BOOGIEROOT)\$(BOOGIEBINDIR)\CodeContractsExtender.pdb"
	copy /y "$(BOOGIEROOT)\$(BOOGIEBINDIR)\ParserHelper.dll"
	copy /y "$(BOOGIEROOT)\$(BOOGIEBINDIR)\ParserHelper.pdb"
	copy /y "$(BOOGIEROOT)\$(BOOGIEBINDIR)\Microsoft.Contracts.dll"

